### ISSUE TITLE
Can't create new untutorial

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#21]
As Frank.Gehry / architect, I created a new untutorial but cannot save/create it. When I click Save, it says Step 1 is required, even though I've made it.

**Comment by awesomeisfree** [comment]
fixed

**Comment by madduccino** [comment]
Still an issue for me. As Serena.Williams, I get the error that "Step x is too short." The console says :

![image](https://user-images.githubusercontent.com/2099441/92332670-90295f80-f04d-11ea-9490-bccec6b87654.png)

![image](https://user-images.githubusercontent.com/2099441/92332639-6cfeb000-f04d-11ea-9d93-0683eaa72e31.png)
