### ISSUE TITLE
Can't edit the level of untutorial

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#34]
The select input won't accept other values than 1.

**Comment by awesomeisfree** [comment]
I've fixed this a couple times now. I think you keep merging over it. You can't put formatting inside the 'text' field of the tcseditor. If you want formatting, put it outside. Level is a numeric field. "Level 3" makes it wig out.

**Comment by madduccino** [comment]
Noted! It still doesn't work for me though. It says Level is outside range........ And is only {untutorial.Levell} in the text field.

**Comment by madduccino** [comment]
Level is still being treated as a string even though there is no formatting in the "text" field:

![image](https://user-images.githubusercontent.com/2099441/96387523-ac520d80-1170-11eb-81dd-4bea91ff9a78.png)

I added parseInt() to validateLevel() which solved the problem but not sure if that takes some of the validation steps out of the function:

![image](https://user-images.githubusercontent.com/2099441/96387549-dd324280-1170-11eb-94b8-fcd544e91174.png)
